
---

common:
  - .Xmodmap
  - .bash_aliases
  - .ctags
  - .gemrc
  - .gitconfig
  - .my.gitconfig
  - .peco
  - .pryrc
  - .tigrc
  - .tmux.conf
  - .tmux
  - .vimperatorrc
  - .vimperator

darwin:
  - .bash_profile
  - .xvimrc
  - Brewfile.sh

linux:
  - local/bin/update-vim

