
---

common:
  - .Xmodmap
  - .bash_aliases
  - .ctags
  - .gemrc
  - .gitconfig
  - .gitignore_global
  - .my.gitconfig
  - .peco
  - .pryrc
  - .psqlrc
  - .ptconfig.toml
  - .tigrc
  - .tmux
  - .tmux.conf
  - .vimperator
  - .vimperatorrc
  - local/bin/binize
  - local/bin/git-archive-dot
  - local/bin/imgcat

darwin:
  - .alacritty.yml
  - .bash_profile
  - .xvimrc
  - .vimrc_first.vim
  - Brewfile.sh

linux:
  - local/bin/update-vim
  - local/bin/update-vim-plugins
  - .dircolors

